#production:
#  cloud_name: <%= ENV['cloud_name'] %>
#  cloudinary_api_key: <%= ENV['cloudinary_api_key'] %>
#  cloudinary_api_secret: <%= ENV['cloudinary_api_secret'] %>
#  enhance_image_tag: true
#  static_file_support: true

development:
  cloud_name: 'dd69eghxe'
  api_key: '773622867178954'
  api_secret: 'pPl3NLzglIqsUcZKbtYYuCWuB-g'
  enhance_image_tag: true
  static_file_support: true
production:
  cloud_name: 'dd69eghxe'
  api_key: '773622867178954'
  api_secret: 'pPl3NLzglIqsUcZKbtYYuCWuB-g'
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: 'dd69eghxe'
  api_key: '773622867178954'
  api_secret: 'pPl3NLzglIqsUcZKbtYYuCWuB-g'
  enhance_image_tag: true
  static_file_support: false