production:
  cloud_name: <%= ENV['cloud_name'] %>
  cloudinary_api_key: <%= ENV['cloudinary_api_key'] %>
  cloudinary_api_secret: <%= ENV['cloudinary_api_secret'] %>
  enhance_image_tag: true
  static_file_support: true